CREATE TABLE users (
id INTEGER PRIMARY KEY AUTO_INCREMENT,
Username VARCHAR(100) NOT NULL,
email VARCHAR(255) NOT NULL UNIQUE,
hash_password VARCHAR(255) NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE categories (
id INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
NAME VARCHAR(255),
user_id INTEGER NOT NULL,
FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE transactions (
id INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
category_id INTEGER NOT NULL,
transaction_type ENUM('INCOME', 'EXPENSE') NOT NULL,
amount DECIMAL(10,2),
DESCRIPTION TEXT,
CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY (category_id) REFERENCES categories(id)
);

CREATE TABLE subscriptions (
id INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
user_id INTEGER NOT NULL,
name VARCHAR(255) NOT NULL,
amount DECIMAL(10,2) NOT NULL,
billing_cycle ENUM('MONTHLY', 'YEARLY') NOT NULL,
next_payment_date DATE NOT NULL,
is_active TINYINT(1) NOT NULL DEFAULT 1,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT NULL, 
FOREIGN KEY (user_id) REFERENCES users(id)
ON DELETE CASCADE
);
